#Profile file. Runs on login. 
export ZDOTDIR="$HOME/.config/zsh"
export PATH=$PATH:$HOME/.local/bin
export EDITOR="vim"
export TERMINAL="st"
export BROWSER="brave"
export TERM='xterm'
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XAUTHORITY=/tmp/Xauthority
export GNUPGHOME="$XDG_DATA_HOME/gnupg"


#Startx Automatically
if [[ -z "$DISPLAY" ]] && [[ $(tty) = /dev/tty1 ]]; then
startx
fi
