abbr fishconf "$EDITOR ~/.config/fish/config.fish"
abbr fishabbr "$EDITOR ~/.config/fish/shortcuts.fish"
abbr vimconf "$EDITOR ~/.vimrc"
abbr termconf "$EDITOR ~/.config/alacritty/"
abbr mkdir 'mkdir -p'
abbr fvpn 'sudo openfortivpn'
abbr kubeon 'kube_ps on'
abbr kubeof 'kube_ps off'
abbr rsync 'rsync -avzhP'